#!/bin/bash
# Script to compile LaTeX files generated by PlotNeuralNet
# Usage: bash tikzmake.sh <filename_without_extension>

if [ $# -eq 0 ]; then
    echo "Usage: bash tikzmake.sh <filename_without_extension>"
    echo "Example: bash tikzmake.sh nnast_architecture"
    exit 1
fi

FILENAME=$1
TEXFILE="${FILENAME}.tex"
PDFFILE="${FILENAME}.pdf"

if [ ! -f "$TEXFILE" ]; then
    echo "Error: $TEXFILE not found"
    exit 1
fi

echo "Compiling $TEXFILE..."

# Compile LaTeX to PDF
pdflatex -interaction=nonstopmode "$TEXFILE" > /dev/null 2>&1
pdflatex -interaction=nonstopmode "$TEXFILE" > /dev/null 2>&1

# Clean up auxiliary files
rm -f "${FILENAME}.aux" "${FILENAME}.log" "${FILENAME}.out"

if [ -f "$PDFFILE" ]; then
    echo "✓ Successfully generated $PDFFILE"
    echo "  You can also generate PNG/SVG using:"
    echo "  pdf2svg $PDFFILE ${FILENAME}.svg"
    echo "  convert -density 300 $PDFFILE ${FILENAME}.png"
else
    echo "✗ Failed to generate PDF. Check ${FILENAME}.log for errors."
    exit 1
fi
